# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dc7g1aiK5asb4yoek2aeOiKX-OG7HvAM

## **Assignment**

1. Find the data type of a if a=9
"""

a = 9
print(type(a))

"""2. Find the data type of a if a=9.0"""

a = 9.0
print(type(a))

"""3. Find the data type of a if a='9.'"""

a = '9.'
print(type(a))

"""4. Find the data type of a if a=(9)"""

a = (9)
print(type(a))

a = (9,2)
print(type(a))

"""5. Find the data type of a if a=False"""

a = False
print(type(a))

"""6. Find the data type of a if a=[1,2,3]"""

a = [1, 2, 3]
print(type(a))

"""7. Find the data type of a if a=(1,2,3)"""

a=(1,2,3)
print(type(a))

"""8. Find the data type of a if a={'key': 9}"""

a={'key': 9}
print(type(a))

"""9. Find the data type of a if a=1 + 9j"""

a=1 + 9j
print(type(a))

"""10. Set a=1 and b=2. What data type is a/b?"""

a = 1
b = 2
print(type(a/b))

"""11. Create a dictionary numbers = {'one':1, 'two':2, 'three':3}. Pull out the number '2' by calling the key 'two'
.
"""

numbers = {'one':1, 'two':2, 'three':3}
print(numbers['two'])

"""12. Create a tuple with the numbers 8, 9, and 10?"""

tup = (8, 9, 10)
print(type(tup))

"""1. Run the following lines of code and explain the error in your own words. Then rewrite the lines of code to run error free:
d = {one:1, two:2, three:3} d[one]
"""

d = {one:1, two:2, three:3} 
d[one]

"""While declaring a dictionary if we are using string for keys then it should be withing quotes, else it will be error. If keys are number then we can ignore the quotes."""

d = {'one':1, 'two':2, 'three':3} 
d['one']

"""14 Run the following lines of code and explain the error in your own words. Then rewrite the lines of code to run error free:

f = false 
    not f
"""

f = false 
not f

"""Here we need to write "False" instead of "false" as it is a keyword and case sensitive."""

f = False 
not f

"""1. Run the following lines of code and explain the error in your own words. Then rewrite the lines of code to run error free:

lst = [1,3,5] 
    lst[3]
"""

lst = [1,3,5] 
lst[3]

"""In coding index starts from 0, here there are 3 elements in the list but it starts from 0. It will go like 0, 1, 2. Which means that 2 is the last element but we are calling 3. So, it gives error."""

lst = [1,3,5] 
print(lst[2])
print(lst[-1])

